backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "archive-episodes"
    label: "Archive-episodes"
    folder: "archive-episodes"
    create: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Template", name: "layout", widget: "hidden", default: "layouts/archive-episode.njk" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "archive" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Text", name: "perex", widget: "string" }
      - { label: "Premiere date", name: "datum", widget: "string" }
      - { label: "Image 357x206", name: "foto", widget: "image" }
      - { label: "Image label", name: "alt", widget: "string" }
      - { label: "URL to TV archive", name: "link", widget: "string" }
      - { label: "Content", name: "body", widget: "hidden" }
  - name: "hero-episodes"
    label: "Hero-episodes"
    folder: "hero-episodes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Template", name: "layout", widget: "hidden", default: "layouts/hero-episode.njk" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "hero" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Premiere date", name: "datum", widget: "string" }
      - { label: "Image 1024x768", name: "foto1024", widget: "image" }
      - { label: "Image 1440x825", name: "foto1440", widget: "image" }
      - { label: "Image label", name: "alt", widget: "string" }
      - { label: "URL to TV archive", name: "link", widget: "string" }
      - { label: "Content", name: "body", widget: "hidden" }
  - name: "cz-hero-episodes"
    label: "CZ-hero-episodes"
    folder: "cz-hero-episodes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Template", name: "layout", widget: "hidden", default: "layouts/non-en-hero-episode.njk" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "czhero" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Premiere date", name: "datum", widget: "string" }
      - { label: "Image 1024x768", name: "foto1024", widget: "string" }
      - { label: "Image 1440x825", name: "foto1440", widget: "string" }
      - { label: "Image label", name: "alt", widget: "string" }
      - { label: "URL to TV archive", name: "link", widget: "string" }
      - { label: "Content", name: "body", widget: "hidden" }
      - { label: "Header", name: "header", widget: "hidden", default: "Poslední díl" }
      - { label: "TV", name: "tv", widget: "hidden", default: "ČT 2" }
      - { label: "Button", name: "cta", widget: "hidden", default: "Přehrát díl" }
      - { label: "Logo", name: "logo", widget: "hidden", default: "logo_DVOJKA_biele.svg" }
  - name: "sk-hero-episodes"
    label: "SK-hero-episodes"
    folder: "sk-hero-episodes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Template", name: "layout", widget: "hidden", default: "layouts/non-en-hero-episode.njk" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "skhero" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Premiere date", name: "datum", widget: "string" }
      - { label: "Image 1024x768 name", name: "foto1024", widget: "string" }
      - { label: "Image 1440x825 name", name: "foto1440", widget: "string" }
      - { label: "Image label", name: "alt", widget: "string" }
      - { label: "URL to TV archive", name: "link", widget: "string" }
      - { label: "Content", name: "body", widget: "hidden" }
      - { label: "Header", name: "header", widget: "hidden", default: "Posledný diel" }
      - { label: "TV", name: "tv", widget: "hidden", default: "RTVS: 2" }
      - { label: "Button", name: "cta", widget: "hidden", default: "Prehrať diel" }
      - { label: "Logo", name: "logo", widget: "hidden", default: "logo_DVOJKA_biele.svg" }
  - name: "pl-hero-episodes"
    label: "PL-hero-episodes"
    folder: "pl-hero-episodes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Template", name: "layout", widget: "hidden", default: "layouts/non-en-hero-episode.njk" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "plhero" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Premiere date", name: "datum", widget: "string" }
      - { label: "Image 1024x768 name", name: "foto1024", widget: "string" }
      - { label: "Image 1440x825 name", name: "foto1440", widget: "string" }
      - { label: "Image label", name: "alt", widget: "string" }
      - { label: "URL to TV archive", name: "link", widget: "string" }
      - { label: "Content", name: "body", widget: "hidden" }
      - { label: "Header", name: "header", widget: "hidden", default: "Posledný diel" }
      - { label: "TV", name: "tv", widget: "hidden", default: "TVP 3" }
      - { label: "Button", name: "cta", widget: "hidden", default: "Prehrať diel" }
      - { label: "Logo", name: "logo", widget: "hidden", default: "logo_DVOJKA_biele.svg" }
  - name: "hu-hero-episodes"
    label: "HU-hero-episodes"
    folder: "hu-hero-episodes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Template", name: "layout", widget: "hidden", default: "layouts/non-en-hero-episode.njk" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "huhero" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Premiere date", name: "datum", widget: "string" }
      - { label: "Image 1024x768 name", name: "foto1024", widget: "string" }
      - { label: "Image 1440x825 name", name: "foto1440", widget: "string" }
      - { label: "Image label", name: "alt", widget: "string" }
      - { label: "URL to TV archive", name: "link", widget: "string" }
      - { label: "Content", name: "body", widget: "hidden" }
      - { label: "Header", name: "header", widget: "hidden", default: "Posledný diel" }
      - { label: "TV", name: "tv", widget: "hidden", default: "Duna TV" }
      - { label: "Button", name: "cta", widget: "hidden", default: "Prehrať diel" }
      - { label: "Logo", name: "logo", widget: "hidden", default: "logo_DVOJKA_biele.svg" }




